#MODULES    
#TYPES OF MODULES : OWN; BUILT-IN
#TYPES OF BUILT-IN MODUELS:

#MATH MODULE: CALCULATES MATHEMATICAL FUNTIONS
import math
print(math.pi)

#RANDOM MODULE: GENERATES RANDOM NUMBERS
import random
print(random.randint(0,10000))

#TIME MODULES: MANIPULATES DATES & TIMES
import datetime
print(datetime.datetime.now())

#OPERATING SYSTEM MODULE: PROVIDES A WAY OF USING THE OS DEPENDING FUNCIONS
import os
print(os.getcwd())

#SYS MODULE: IMPORTS SYS
#PRINTS THE CURRENT VERSION OF PYTHON
import sys
print(sys.version)

#THESE ARE SOME EXAMPLES OF THE PYTHON BUILT-IN MODULES
#PYTHON STANDARD LIBRARY